version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # The --reload flag is great for development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
